version: "2.1"

services:
  redis:
    image: "redis:4.0.14"
    container_name: "kolau_scheduler_redis"
    ports:
      - "127.0.0.1:6379:6379"

  postgresql:
    image: "postgres:11"
    container_name: "kolau_scheduler_postgresql"
    ports:
      - "127.0.0.1:5432:5432"
