default: &default
  adapter: postgresql
  pool: 20
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: kolau_scheduler_development
  host: localhost
  username: postgres

test:
  <<: *default
  database: kolau_scheduler_test
  host: localhost
  username: postgres

production:
  <<: *default
  pool: 60
